### PR TITLE
PLAT-424 Add license information for derbyclient

### PR DESCRIPTION
**Pull request by ilx**

### CODE REVIEW

**Comment by hierynomus** [comment]
Why? What is this needed for?

**Comment by ilx** [comment]
so that "cluster PR" in XLR goes green

**Comment by hierynomus** [comment]
Why do we need derbyclient? What is it?

**Comment by ilx** [comment]
it contains drivers for derby network server: https://db.apache.org/derby/papers/DerbyClientSpec.html

**Comment by ilx** [comment]
Or I can just delete that dependency so if someone needs it he can configure it by himself?

**Pull request closed without merging**
